"use client";

import React from 'react';
import { createClient } from '@/utils/supabase/client';
const supabase = createClient();
import { Download } from 'lucide-react';
import ChatSidebar from '@/components/Chat';

type ResultsViewProps = {
  showChat: boolean;
  isDarkMode: boolean;
  theme: any;
  onShowChat: (show: boolean) => void;
  summaryResult: Record<string, string> | null;
  documentId?: string | number | null;
  userId?: string | null;
  pdfTitle?: string;
  uploadDate?: string;
};

export default function ResultsView({
  showChat,
  isDarkMode,
  theme,
  onShowChat,
  summaryResult,
  documentId,
  userId,
  pdfTitle,
  uploadDate,
}: ResultsViewProps) {
  // Download PDF logic
  const handleDownload = async () => {
    if (!documentId) return;
    // Fetch document record from Supabase
    const { data, error } = await supabase
      .from('documents')
      .select('file_url, file_type, title')
      .eq('id', documentId)
      .single();
    if (error || !data?.file_url) {
      alert('Could not find file for this document.');
      return;
    }
    // Fix: Supabase public URL must be /storage/v1/object/public/<bucket>/<path>
    // If file_url already includes the bucket, remove it
    // Use Supabase's getPublicUrl (if bucket is public) or createSignedUrl (if not)
    // Always use signed URL for private bucket
    const filePath = data.file_url;
    const { data: signedData, error: signedError } = await supabase.storage.from('documents').createSignedUrl(filePath, 120);
    if (signedData?.signedUrl) {
      try {
        const response = await fetch(signedData.signedUrl);
        if (!response.ok) throw new Error('Failed to fetch file');
        const blob = await response.blob();
        const a = document.createElement('a');
        a.href = window.URL.createObjectURL(blob);
        let filename = 'document.pdf';
        if (data.title) {
          filename = data.title.match(/\.pdf$/i) ? data.title : `${data.title}.pdf`;
        }
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        setTimeout(() => {
          window.URL.revokeObjectURL(a.href);
          document.body.removeChild(a);
        }, 100);
      } catch (err) {
        alert('Failed to download file.');
      }
    } else {
      alert('Could not generate a download link.');
    }
  };

  return (
    <>
      <div className="max-w-5xl mx-auto w-full">
        {/* Paper Info Card */}
        <div className={`${theme.cardBg} ${isDarkMode ? 'backdrop-blur-xl' : ''} rounded-xl shadow-lg border ${theme.cardBorder} p-4 sm:p-6 mb-4 sm:mb-6`}>
          <div className="flex items-start justify-between gap-3">
            <div className="flex-1 min-w-0">
              <h3 className={`text-base sm:text-lg md:text-xl font-bold ${theme.text} mb-2`}>
                {pdfTitle || 'Paper Summary'}
              </h3>
              <p className={`text-xs sm:text-sm ${theme.textTertiary}`}>
                {uploadDate || 'Results generated by PARSeAI'}
              </p>
            </div>
            <div className="flex gap-2 shrink-0">
              <button className={`p-1.5 sm:p-2 ${theme.hoverBg} rounded-lg transition-colors cursor-pointer`} title="Download" onClick={handleDownload}>
                <Download className={`w-4 h-4 sm:w-5 sm:h-5 ${theme.textSecondary}`} />
              </button>
            </div>
          </div>
        </div>

        {/* Summaries Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 sm:gap-4">
          {summaryResult && Object.keys(summaryResult).length > 0 ? (
            <>
              {/* Main Sections */}
              {['Abstract', 'Introduction', 'Methodology', 'Results', 'Conclusion'].map((section, idx) => {
                if (!summaryResult[section]) return null;
                const gradients = [
                  'linear-gradient(135deg, rgba(99,102,241,0.8) 0%, rgba(78,70,197,0.8) 60%, rgba(45,42,120,1) 100%)',
                  'linear-gradient(160deg, rgba(34,211,238,0.8) 0%, rgba(24,170,190,0.8) 60%, rgba(8,120,130,1) 100%)',
                  'linear-gradient(135deg, rgba(139,92,246,0.8) 0%, rgba(105,70,200,0.8) 60%, rgba(70,42,160,1) 100%)',
                  'linear-gradient(135deg, rgba(99,102,241,0.8) 0%, rgba(78,70,197,0.8) 60%, rgba(45,42,120,1) 100%)',
                  'linear-gradient(135deg, rgba(99,102,241,0.8) 0%, rgba(78,70,197,0.8) 60%, rgba(45,42,120,1) 100%)'
                ];
                return (
                  <div 
                    key={section} 
                    className="rounded-xl shadow-lg p-4 sm:p-6 transition-transform duration-300 hover:-translate-y-1"
                    style={{ background: gradients[idx] }}
                  >
                    <h4 className="text-base sm:text-lg font-bold text-white mb-2 sm:mb-3 flex items-center gap-2">
                      <span className="w-7 h-7 sm:w-8 sm:h-8 bg-white/20 text-white rounded-lg flex items-center justify-center text-sm font-bold border border-white/30">
                        {idx + 1}
                      </span>
                      {section}
                    </h4>
                    <p className="text-white/90 leading-relaxed text-sm sm:text-base text-justify">
                      {summaryResult[section]}
                    </p>
                  </div>
                );
              })}

              {/* Keyword Definitions Section */}
              {summaryResult["Definitions"] && Object.keys(summaryResult["Definitions"]).length > 0 && (
                <div className="rounded-xl shadow-lg p-4 sm:p-6 transition-transform duration-300 hover:-translate-y-1"
                  style={{ background: 'linear-gradient(120deg, #6366F1 0%, #22D3EE 100%)' }}>
                  <h4 className="text-base sm:text-lg font-bold text-white mb-2 sm:mb-3 flex items-center gap-2">
                    <span className="w-7 h-7 sm:w-8 sm:h-8 bg-white/20 text-white rounded-lg flex items-center justify-center text-sm font-bold border border-white/30">
                      ℹ️
                    </span>
                    Keyword Definitions
                  </h4>
                  <ul className="text-white/90 leading-relaxed text-sm sm:text-base list-disc pl-5">
                    {Object.entries(summaryResult["Definitions"]).map(([kw, def]) => (
                      <li key={kw}><strong>{kw}:</strong> {def}</li>
                    ))}
                  </ul>
                </div>
              )}
            </>
          ) : (
            <div className="text-center text-white/70 py-8">No summary available.</div>
          )}
        </div>
      </div>

      {/* Chat Sidebar */}
      {showChat && (
        <ChatSidebar
          isDarkMode={isDarkMode}
          theme={theme}
          onClose={() => onShowChat(false)}
          documentId={documentId ?? null}
          userId={userId ?? null}
          uploadDate={uploadDate}
        />
      )}
    </>
  );
}
